### ISSUE TITLE
Action condition for Prot Pally not supported

### ISSUE THREAD

**Issue by jodysaliba** [insaneKane/simpl#7]
I ran SimulationCraft for my prot pally and bot threw an exception when trying to start the BotBase:

<18:06>:Line 79,182	: 'Simcraft.SimcraftImpl' does not contain a definition for 'time_to_hpg' and no extension method 'time_to_hpg' accepting a first argument of type 'Simcraft.SimcraftImpl' could be found (are you missing a using directive or an assembly reference?) - line c:\Users\jody\AppData\Local\Temp\ejymw12k.0.cs(79,182) : error CS1061: 'Simcraft.SimcraftImpl' does not contain a definition for 'time_to_hpg' and no extension method 'time_to_hpg' accepting a first argument of type 'Simcraft.SimcraftImpl' could be found (are you missing a using directive or an assembly reference?)

**Comment by insaneKane** [comment]
Heal and Tank specs are not supported :(
